"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Plus, X } from "lucide-react";

export default function PaymentForm(){
 const [open,setOpen]=useState(false); const [busy,setBusy]=useState(false); const router=useRouter();
 async function submit(e:React.FormEvent<HTMLFormElement>){ e.preventDefault(); setBusy(true); const fd=new FormData(e.currentTarget); const payload=Object.fromEntries(fd.entries()); const r=await fetch('/api/payments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); setBusy(false); if(r.ok){setOpen(false); router.refresh();}}
 return <>{<button className="btn primary" onClick={()=>setOpen(true)}><Plus size={17}/> Nova conta</button>}{open&&<div className="modal-wrap"><div className="modal-card"><div className="modal-head"><div><h2>Nova conta</h2><p>Cadastre um pagamento e defina sua prioridade.</p></div><button className="icon-btn" onClick={()=>setOpen(false)}><X/></button></div><form className="grid-form" onSubmit={submit}><label className="span2">Nome da conta<input name="name" placeholder="Ex.: Aluguel" required/></label><label>Valor<input name="amount" type="number" step="0.01" min="0.01" placeholder="0,00" required/></label><label>Vencimento<input name="dueDate" type="date" required/></label><label>Categoria<select name="category"><option>Moradia</option><option>Alimentação</option><option>Transporte</option><option>Saúde</option><option>Educação</option><option>Lazer</option><option>Cartão</option><option>Outros</option></select></label><label>Prioridade<select name="priority"><option value="ESSENTIAL">Essencial</option><option value="HIGH">Alta</option><option value="MEDIUM">Média</option><option value="LOW">Baixa</option></select></label><label>Recorrência<select name="recurrence"><option value="NONE">Não recorrente</option><option value="MONTHLY">Mensal</option><option value="YEARLY">Anual</option></select></label><label>Status<select name="status"><option value="PENDING">A pagar</option><option value="PAID">Pago</option><option value="PARTIAL">Parcial</option></select></label><label className="span2">Observações<textarea name="notes" placeholder="Informações opcionais"/></label><div className="modal-actions span2"><button type="button" className="btn secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="btn primary" disabled={busy}>{busy?'Salvando...':'Salvar conta'}</button></div></form></div></div>}</>
}
